dist: precise
sudo: false
language: php
php:
  - '5.2'
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
# PHP 7 currently fails to run our tests, due to PHPUnit compatibility issues.
# TODO: Provide a shim so that later, namespaced, PHPUnit versions work properly.
#  - '7.0'
#  - '7.1'
script: phpunit tests
